// Palette data after `bzz` is adapted from gammons/slk at
// 8149c3b18ed04c259efe5feb545d040ab043d922 under the MIT license.
// See THIRD_PARTY_LICENSES.md for attribution and the complete notice.
use super::Palette;
pub(super) static PALETTES: &[Palette] = &[
    Palette {
        id: "bzz",
        name: "bzz",
        primary: "cyan",
        accent: "yellow",
        warning: "yellow",
        error: "red",
        background: "terminal_default",
        surface: "#262630",
        surface_dark: "dark_gray",
        text: "terminal_default",
        text_muted: "dark_gray",
        border: "terminal_default",
        sidebar_background: "none",
        sidebar_text: "terminal_default",
        sidebar_text_muted: "dark_gray",
        rail_background: "none",
        selection_background: "#262630",
        selection_foreground: "terminal_default",
    },
    Palette {
        id: "dark",
        name: "Dark",
        primary: "#4A9EFF",
        accent: "#50C878",
        warning: "#E0A030",
        error: "#E04040",
        background: "#1A1A2E",
        surface: "#16162B",
        surface_dark: "#0F0F23",
        text: "#E0E0E0",
        text_muted: "#888888",
        border: "#333333",
        sidebar_background: "#0D0D1A",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#060610",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "light",
        name: "Light",
        primary: "#0366D6",
        accent: "#28A745",
        warning: "#D9840D",
        error: "#CB2431",
        background: "#FFFFFF",
        surface: "#F6F8FA",
        surface_dark: "#EAEEF2",
        text: "#24292E",
        text_muted: "#6A737D",
        border: "#D1D5DA",
        sidebar_background: "#24292E",
        sidebar_text: "#F6F8FA",
        sidebar_text_muted: "#8C959F",
        rail_background: "#1B1F23",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "dracula",
        name: "Dracula",
        primary: "#BD93F9",
        accent: "#50FA7B",
        warning: "#FFB86C",
        error: "#FF5555",
        background: "#282A36",
        surface: "#343746",
        surface_dark: "#21222C",
        text: "#F8F8F2",
        text_muted: "#6272A4",
        border: "#44475A",
        sidebar_background: "#14151C",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0C0C10",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "solarized-dark",
        name: "Solarized Dark",
        primary: "#268BD2",
        accent: "#859900",
        warning: "#B58900",
        error: "#DC322F",
        background: "#002B36",
        surface: "#073642",
        surface_dark: "#001E26",
        text: "#839496",
        text_muted: "#586E75",
        border: "#073642",
        sidebar_background: "#001820",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#000C10",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "solarized-light",
        name: "Solarized Light",
        primary: "#268BD2",
        accent: "#859900",
        warning: "#B58900",
        error: "#DC322F",
        background: "#FDF6E3",
        surface: "#EEE8D5",
        surface_dark: "#E4DCCA",
        text: "#657B83",
        text_muted: "#93A1A1",
        border: "#EEE8D5",
        sidebar_background: "#002B36",
        sidebar_text: "#93A1A1",
        sidebar_text_muted: "#586E75",
        rail_background: "#001E26",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "gruvbox-dark",
        name: "Gruvbox Dark",
        primary: "#83A598",
        accent: "#B8BB26",
        warning: "#FABD2F",
        error: "#FB4934",
        background: "#282828",
        surface: "#3C3836",
        surface_dark: "#1D2021",
        text: "#EBDBB2",
        text_muted: "#928374",
        border: "#504945",
        sidebar_background: "#181818",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0E0E0E",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "gruvbox-light",
        name: "Gruvbox Light",
        primary: "#076678",
        accent: "#79740E",
        warning: "#B57614",
        error: "#9D0006",
        background: "#FBF1C7",
        surface: "#EBDBB2",
        surface_dark: "#D5C4A1",
        text: "#3C3836",
        text_muted: "#928374",
        border: "#BDAE93",
        sidebar_background: "#282828",
        sidebar_text: "#EBDBB2",
        sidebar_text_muted: "#A89984",
        rail_background: "#1D2021",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "nord",
        name: "Nord",
        primary: "#88C0D0",
        accent: "#A3BE8C",
        warning: "#EBCB8B",
        error: "#BF616A",
        background: "#2E3440",
        surface: "#3B4252",
        surface_dark: "#242933",
        text: "#ECEFF4",
        text_muted: "#7B88A1",
        border: "#4C566A",
        sidebar_background: "#1B2028",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#11141A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "tokyo-night",
        name: "Tokyo Night",
        primary: "#7AA2F7",
        accent: "#9ECE6A",
        warning: "#E0AF68",
        error: "#F7768E",
        background: "#1A1B26",
        surface: "#24283B",
        surface_dark: "#16161E",
        text: "#C0CAF5",
        text_muted: "#565F89",
        border: "#3B4261",
        sidebar_background: "#262838",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#1A1B26",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "catppuccin-mocha",
        name: "Catppuccin Mocha",
        primary: "#89B4FA",
        accent: "#A6E3A1",
        warning: "#F9E2AF",
        error: "#F38BA8",
        background: "#1E1E2E",
        surface: "#313244",
        surface_dark: "#181825",
        text: "#CDD6F4",
        text_muted: "#6C7086",
        border: "#45475A",
        sidebar_background: "#0E0E16",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#08080F",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "one-dark",
        name: "One Dark",
        primary: "#61AFEF",
        accent: "#98C379",
        warning: "#E5C07B",
        error: "#E06C75",
        background: "#282C34",
        surface: "#2C313C",
        surface_dark: "#21252B",
        text: "#ABB2BF",
        text_muted: "#636D83",
        border: "#3E4452",
        sidebar_background: "#1A1D23",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#101216",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "rose-pine",
        name: "Rosé Pine",
        primary: "#C4A7E7",
        accent: "#9CCFD8",
        warning: "#F6C177",
        error: "#EB6F92",
        background: "#191724",
        surface: "#1F1D2E",
        surface_dark: "#16141F",
        text: "#E0DEF4",
        text_muted: "#6E6A86",
        border: "#26233A",
        sidebar_background: "#262433",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#191724",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "rose-pine-moon",
        name: "Rosé Pine Moon",
        primary: "#C4A7E7",
        accent: "#9CCFD8",
        warning: "#F6C177",
        error: "#EB6F92",
        background: "#232136",
        surface: "#2A273F",
        surface_dark: "#1A1825",
        text: "#E0DEF4",
        text_muted: "#6E6A86",
        border: "#393552",
        sidebar_background: "#15131F",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0C0B12",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "slack-default",
        name: "Slack Default",
        primary: "#1264A3",
        accent: "#007A5A",
        warning: "#ECB22E",
        error: "#E01E5A",
        background: "#FFFFFF",
        surface: "#F8F8F8",
        surface_dark: "#F0F0F0",
        text: "#1D1C1D",
        text_muted: "#616061",
        border: "#DDDDDD",
        sidebar_background: "#434243",
        sidebar_text: "#D1D2D3",
        sidebar_text_muted: "#9A9B9E",
        rail_background: "#2E2C2E",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "monokai",
        name: "Monokai",
        primary: "#66D9EF",
        accent: "#A6E22E",
        warning: "#E6DB74",
        error: "#F92672",
        background: "#272822",
        surface: "#3E3D32",
        surface_dark: "#1E1F1C",
        text: "#F8F8F2",
        text_muted: "#75715E",
        border: "#49483E",
        sidebar_background: "#181811",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0F0F0A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "github-dark",
        name: "GitHub Dark",
        primary: "#58A6FF",
        accent: "#3FB950",
        warning: "#D29922",
        error: "#F85149",
        background: "#0D1117",
        surface: "#161B22",
        surface_dark: "#010409",
        text: "#C9D1D9",
        text_muted: "#8B949E",
        border: "#30363D",
        sidebar_background: "#1C2128",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0D1117",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "ayu-mirage",
        name: "Ayu Mirage",
        primary: "#73D0FF",
        accent: "#BAE67E",
        warning: "#FFD580",
        error: "#F28779",
        background: "#1F2430",
        surface: "#232834",
        surface_dark: "#191E2A",
        text: "#CBCCC6",
        text_muted: "#707A8C",
        border: "#33415E",
        sidebar_background: "#0E121C",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#080C16",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "everforest-dark",
        name: "Everforest Dark",
        primary: "#7FBBB3",
        accent: "#A7C080",
        warning: "#DBBC7F",
        error: "#E67E80",
        background: "#2D353B",
        surface: "#343F44",
        surface_dark: "#232A2E",
        text: "#D3C6AA",
        text_muted: "#859289",
        border: "#3D484D",
        sidebar_background: "#1E2429",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#141819",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "kanagawa",
        name: "Kanagawa",
        primary: "#7FB4CA",
        accent: "#98BB6C",
        warning: "#E6C384",
        error: "#E46876",
        background: "#1F1F28",
        surface: "#2A2A37",
        surface_dark: "#16161D",
        text: "#DCD7BA",
        text_muted: "#727169",
        border: "#363646",
        sidebar_background: "#0C0C10",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#060608",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "material-ocean",
        name: "Material Ocean",
        primary: "#82AAFF",
        accent: "#C3E88D",
        warning: "#FFCB6B",
        error: "#FF5370",
        background: "#0F111A",
        surface: "#1A1C25",
        surface_dark: "#090B10",
        text: "#A6ACCD",
        text_muted: "#4B526D",
        border: "#1F2233",
        sidebar_background: "#2A2D38",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0F111A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "synthwave",
        name: "Synthwave",
        primary: "#36F9F6",
        accent: "#72F1B8",
        warning: "#FEDE5D",
        error: "#FF6E96",
        background: "#241B2F",
        surface: "#2D2139",
        surface_dark: "#1A1226",
        text: "#F8F8F2",
        text_muted: "#848BBD",
        border: "#495495",
        sidebar_background: "#150E20",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0B0714",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "catppuccin-latte",
        name: "Catppuccin Latte",
        primary: "#1E66F5",
        accent: "#40A02B",
        warning: "#DF8E1D",
        error: "#D20F39",
        background: "#EFF1F5",
        surface: "#E6E9EF",
        surface_dark: "#DCE0E8",
        text: "#4C4F69",
        text_muted: "#6C6F85",
        border: "#BCC0CC",
        sidebar_background: "#1E1E2E",
        sidebar_text: "#CDD6F4",
        sidebar_text_muted: "#9399B2",
        rail_background: "#181825",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "github-light",
        name: "GitHub Light",
        primary: "#0969DA",
        accent: "#1A7F37",
        warning: "#9A6700",
        error: "#CF222E",
        background: "#FFFFFF",
        surface: "#F6F8FA",
        surface_dark: "#EAEEF2",
        text: "#1F2328",
        text_muted: "#656D76",
        border: "#D0D7DE",
        sidebar_background: "#24292F",
        sidebar_text: "#F6F8FA",
        sidebar_text_muted: "#8C959F",
        rail_background: "#1B1F23",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "tokyo-night-light",
        name: "Tokyo Night Light",
        primary: "#34548A",
        accent: "#485E30",
        warning: "#8F5E15",
        error: "#8C4351",
        background: "#D5D6DB",
        surface: "#CBCCD1",
        surface_dark: "#C4C8DA",
        text: "#343B58",
        text_muted: "#6172B0",
        border: "#9699A8",
        sidebar_background: "#1A1B26",
        sidebar_text: "#A9B1D6",
        sidebar_text_muted: "#565F89",
        rail_background: "#16161E",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "atom-one-light",
        name: "Atom One Light",
        primary: "#4078F2",
        accent: "#50A14F",
        warning: "#C18401",
        error: "#E45649",
        background: "#FAFAFA",
        surface: "#F0F0F0",
        surface_dark: "#E5E5E6",
        text: "#383A42",
        text_muted: "#A0A1A7",
        border: "#D3D3D3",
        sidebar_background: "#282C34",
        sidebar_text: "#ABB2BF",
        sidebar_text_muted: "#5C6370",
        rail_background: "#21252B",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "catppuccin-frappe",
        name: "Catppuccin Frappé",
        primary: "#8CAAEE",
        accent: "#A6D189",
        warning: "#E5C890",
        error: "#E78284",
        background: "#303446",
        surface: "#414559",
        surface_dark: "#292C3C",
        text: "#C6D0F5",
        text_muted: "#838BA7",
        border: "#51576D",
        sidebar_background: "#1E212C",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#14161D",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "catppuccin-macchiato",
        name: "Catppuccin Macchiato",
        primary: "#8AADF4",
        accent: "#A6DA95",
        warning: "#EED49F",
        error: "#ED8796",
        background: "#24273A",
        surface: "#363A4F",
        surface_dark: "#1E2030",
        text: "#CAD3F5",
        text_muted: "#6E738D",
        border: "#494D64",
        sidebar_background: "#181A28",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0F1020",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "tokyo-night-storm",
        name: "Tokyo Night Storm",
        primary: "#7AA2F7",
        accent: "#9ECE6A",
        warning: "#E0AF68",
        error: "#F7768E",
        background: "#24283B",
        surface: "#2F334D",
        surface_dark: "#1F2335",
        text: "#C0CAF5",
        text_muted: "#565F89",
        border: "#3B4261",
        sidebar_background: "#181B29",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0F1019",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "cobalt2",
        name: "Cobalt2",
        primary: "#FFC600",
        accent: "#3AD900",
        warning: "#FF9D00",
        error: "#FF628C",
        background: "#193549",
        surface: "#1F4662",
        surface_dark: "#15232D",
        text: "#E1EFFF",
        text_muted: "#6E96B5",
        border: "#0D3A58",
        sidebar_background: "#0C2030",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#06141F",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "iceberg",
        name: "Iceberg",
        primary: "#84A0C6",
        accent: "#B4BE82",
        warning: "#E2A478",
        error: "#E27878",
        background: "#161821",
        surface: "#1E2132",
        surface_dark: "#0F1117",
        text: "#C6C8D1",
        text_muted: "#6B7089",
        border: "#2E313F",
        sidebar_background: "#242736",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#161821",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "oceanic-next",
        name: "Oceanic Next",
        primary: "#6699CC",
        accent: "#99C794",
        warning: "#FAC863",
        error: "#EC5F67",
        background: "#1B2B34",
        surface: "#343D46",
        surface_dark: "#16232B",
        text: "#CDD3DE",
        text_muted: "#65737E",
        border: "#4F5B66",
        sidebar_background: "#0A1620",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#06121A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "cyberpunk-neon",
        name: "Cyberpunk Neon",
        primary: "#0ABDC6",
        accent: "#00FF9C",
        warning: "#FCEE0C",
        error: "#EA00D9",
        background: "#000B1E",
        surface: "#0D1B2A",
        surface_dark: "#000814",
        text: "#D7D7D7",
        text_muted: "#7E7E8E",
        border: "#133E7C",
        sidebar_background: "#0D1B2A",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#000814",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "material-palenight",
        name: "Material Palenight",
        primary: "#82AAFF",
        accent: "#C3E88D",
        warning: "#FFCB6B",
        error: "#FF5370",
        background: "#292D3E",
        surface: "#34324A",
        surface_dark: "#1F1F2E",
        text: "#A6ACCD",
        text_muted: "#676E95",
        border: "#3A3F58",
        sidebar_background: "#1B1B28",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#111119",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "hot-dog-stand",
        name: "Hot Dog Stand",
        primary: "#FF0000",
        accent: "#000000",
        warning: "#FF8000",
        error: "#800000",
        background: "#FFFF00",
        surface: "#FFFF80",
        surface_dark: "#FFCC00",
        text: "#000000",
        text_muted: "#7F6F00",
        border: "#FF0000",
        sidebar_background: "#FF0000",
        sidebar_text: "#FFFF00",
        sidebar_text_muted: "#FFCC00",
        rail_background: "#800000",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "ansi-dark",
        name: "ANSI Dark",
        primary: "blue",
        accent: "cyan",
        warning: "yellow",
        error: "red",
        background: "black",
        surface: "dark_gray",
        surface_dark: "black",
        text: "white",
        text_muted: "dark_gray",
        border: "dark_gray",
        sidebar_background: "",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "ansi-light",
        name: "ANSI Light",
        primary: "blue",
        accent: "cyan",
        warning: "yellow",
        error: "red",
        background: "white",
        surface: "gray",
        surface_dark: "gray",
        text: "black",
        text_muted: "dark_gray",
        border: "dark_gray",
        sidebar_background: "",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "zenburn",
        name: "Zenburn",
        primary: "#8CD0D3",
        accent: "#7F9F7F",
        warning: "#F0DFAF",
        error: "#CC9393",
        background: "#3F3F3F",
        surface: "#4F4F4F",
        surface_dark: "#2B2B2B",
        text: "#DCDCCC",
        text_muted: "#989890",
        border: "#5F5F5F",
        sidebar_background: "#2B2B2B",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#1F1F1F",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "gruvbox-material-dark",
        name: "Gruvbox Material Dark",
        primary: "#7DAEA3",
        accent: "#A9B665",
        warning: "#D8A657",
        error: "#EA6962",
        background: "#282828",
        surface: "#32302F",
        surface_dark: "#1D2021",
        text: "#D4BE98",
        text_muted: "#928374",
        border: "#45403D",
        sidebar_background: "#1A1A1A",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0F0F0F",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "nightfox",
        name: "Nightfox",
        primary: "#719CD6",
        accent: "#81B29A",
        warning: "#DBC074",
        error: "#C94F6D",
        background: "#192330",
        surface: "#212E3F",
        surface_dark: "#131A24",
        text: "#CDCECF",
        text_muted: "#738091",
        border: "#2B3B51",
        sidebar_background: "#0E141C",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#080B11",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "carbonfox",
        name: "Carbonfox",
        primary: "#78A9FF",
        accent: "#25BE6A",
        warning: "#FF832B",
        error: "#EE5396",
        background: "#161616",
        surface: "#262626",
        surface_dark: "#0C0C0C",
        text: "#F2F4F8",
        text_muted: "#7B7C7E",
        border: "#393939",
        sidebar_background: "#242424",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0C0C0C",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "melange-dark",
        name: "Melange Dark",
        primary: "#A3A9CE",
        accent: "#85B695",
        warning: "#EBC06D",
        error: "#D47766",
        background: "#292522",
        surface: "#34302C",
        surface_dark: "#1F1B18",
        text: "#ECE1D7",
        text_muted: "#867462",
        border: "#403A36",
        sidebar_background: "#16130F",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0D0B09",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "vesper",
        name: "Vesper",
        primary: "#FFC799",
        accent: "#99FFE4",
        warning: "#FFC799",
        error: "#FF8080",
        background: "#101010",
        surface: "#1C1C1C",
        surface_dark: "#0A0A0A",
        text: "#FFFFFF",
        text_muted: "#8B8B8B",
        border: "#2A2A2A",
        sidebar_background: "#1F1F1F",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#000000",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "flexoki-dark",
        name: "Flexoki Dark",
        primary: "#4385BE",
        accent: "#879A39",
        warning: "#D0A215",
        error: "#D14D41",
        background: "#100F0F",
        surface: "#1C1B1A",
        surface_dark: "#0A0908",
        text: "#CECDC3",
        text_muted: "#878580",
        border: "#282726",
        sidebar_background: "#201F1E",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0A0908",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "modus-vivendi",
        name: "Modus Vivendi",
        primary: "#2FAFFF",
        accent: "#44BC44",
        warning: "#FEC43F",
        error: "#FF5F59",
        background: "#000000",
        surface: "#1E1E1E",
        surface_dark: "#0A0A0A",
        text: "#FFFFFF",
        text_muted: "#989898",
        border: "#303030",
        sidebar_background: "#1A1A1A",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0A0A0A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "night-owl",
        name: "Night Owl",
        primary: "#82AAFF",
        accent: "#ADDB67",
        warning: "#ECC48D",
        error: "#EF5350",
        background: "#011627",
        surface: "#0E293F",
        surface_dark: "#010E1A",
        text: "#D6DEEB",
        text_muted: "#5F7E97",
        border: "#1D3B53",
        sidebar_background: "#0E293F",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#010E1A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "poimandres",
        name: "Poimandres",
        primary: "#89DDFF",
        accent: "#5DE4C7",
        warning: "#FFFAC2",
        error: "#D0679D",
        background: "#1B1E28",
        surface: "#252B37",
        surface_dark: "#171922",
        text: "#E4F0FB",
        text_muted: "#767C9D",
        border: "#303340",
        sidebar_background: "#0F1118",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#08090D",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "ayu-dark",
        name: "Ayu Dark",
        primary: "#39BAE6",
        accent: "#C2D94C",
        warning: "#FFB454",
        error: "#FF3333",
        background: "#0B0E14",
        surface: "#131721",
        surface_dark: "#06080D",
        text: "#BFBDB6",
        text_muted: "#565B66",
        border: "#1B1F28",
        sidebar_background: "#1B202B",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0B0E14",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "kanagawa-dragon",
        name: "Kanagawa Dragon",
        primary: "#8BA4B0",
        accent: "#8A9A7B",
        warning: "#C4B28A",
        error: "#C4746E",
        background: "#181616",
        surface: "#282423",
        surface_dark: "#0D0C0C",
        text: "#C5C9C5",
        text_muted: "#737C73",
        border: "#2D2C29",
        sidebar_background: "#282423",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#100E0E",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "rose-pine-dawn",
        name: "Rosé Pine Dawn",
        primary: "#56949F",
        accent: "#286983",
        warning: "#EA9D34",
        error: "#B4637A",
        background: "#FAF4ED",
        surface: "#FFFAF3",
        surface_dark: "#F2E9E1",
        text: "#575279",
        text_muted: "#797593",
        border: "#DFDAD9",
        sidebar_background: "#575279",
        sidebar_text: "#FAF4ED",
        sidebar_text_muted: "#9893A5",
        rail_background: "#423F5C",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "everforest-light",
        name: "Everforest Light",
        primary: "#3A94C5",
        accent: "#8DA101",
        warning: "#DFA000",
        error: "#F85552",
        background: "#FDF6E3",
        surface: "#F4F0D9",
        surface_dark: "#EFEBD4",
        text: "#5C6A72",
        text_muted: "#939F91",
        border: "#E0DCC7",
        sidebar_background: "#343F44",
        sidebar_text: "#D3C6AA",
        sidebar_text_muted: "#859289",
        rail_background: "#232A2E",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "flexoki-light",
        name: "Flexoki Light",
        primary: "#205EA6",
        accent: "#66800B",
        warning: "#AD8301",
        error: "#AF3029",
        background: "#FFFCF0",
        surface: "#F2F0E5",
        surface_dark: "#E6E4D9",
        text: "#100F0F",
        text_muted: "#6F6E69",
        border: "#DAD8CE",
        sidebar_background: "#100F0F",
        sidebar_text: "#CECDC3",
        sidebar_text_muted: "#878580",
        rail_background: "#1C1B1A",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "modus-operandi",
        name: "Modus Operandi",
        primary: "#0031A9",
        accent: "#006800",
        warning: "#6F5500",
        error: "#A60000",
        background: "#FFFFFF",
        surface: "#F2F2F2",
        surface_dark: "#E5E5E5",
        text: "#000000",
        text_muted: "#595959",
        border: "#D0D0D0",
        sidebar_background: "#1E1E1E",
        sidebar_text: "#FFFFFF",
        sidebar_text_muted: "#989898",
        rail_background: "#000000",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "kanagawa-lotus",
        name: "Kanagawa Lotus",
        primary: "#4D699B",
        accent: "#6F894E",
        warning: "#C4781E",
        error: "#C84053",
        background: "#F2ECBC",
        surface: "#E7DBA0",
        surface_dark: "#DCD5AC",
        text: "#545464",
        text_muted: "#8A8980",
        border: "#DCD5AC",
        sidebar_background: "#1F1F28",
        sidebar_text: "#DCD7BA",
        sidebar_text_muted: "#8A8980",
        rail_background: "#16161D",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "papercolor-light",
        name: "PaperColor Light",
        primary: "#0087AF",
        accent: "#008700",
        warning: "#D75F00",
        error: "#AF0000",
        background: "#EEEEEE",
        surface: "#E4E4E4",
        surface_dark: "#D0D0D0",
        text: "#444444",
        text_muted: "#878787",
        border: "#D0D0D0",
        sidebar_background: "#1C1C1C",
        sidebar_text: "#E4E4E4",
        sidebar_text_muted: "#878787",
        rail_background: "#080808",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "aubergine",
        name: "Aubergine",
        primary: "#1264A3",
        accent: "#007A5A",
        warning: "#ECB22E",
        error: "#E01E5A",
        background: "#FFFFFF",
        surface: "#F8F8F8",
        surface_dark: "#F0F0F0",
        text: "#1D1C1D",
        text_muted: "#616061",
        border: "#DDDDDD",
        sidebar_background: "#4D394B",
        sidebar_text: "#FFFFFF",
        sidebar_text_muted: "#BAA2B8",
        rail_background: "#3E313C",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "ochin",
        name: "Ochin",
        primary: "#4A90D9",
        accent: "#4CA64C",
        warning: "#ECB22E",
        error: "#EB4D5C",
        background: "#FFFFFF",
        surface: "#F6F7F8",
        surface_dark: "#EDEFF1",
        text: "#1D1C1D",
        text_muted: "#616061",
        border: "#DCDFE3",
        sidebar_background: "#303E4D",
        sidebar_text: "#DAE3ED",
        sidebar_text_muted: "#8B97A5",
        rail_background: "#232D38",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "choco-mint",
        name: "Choco Mint",
        primary: "#16A085",
        accent: "#16C098",
        warning: "#D9A441",
        error: "#C0563B",
        background: "#FAF7F2",
        surface: "#F0EBE3",
        surface_dark: "#E6DFD5",
        text: "#2B2017",
        text_muted: "#6E6258",
        border: "#DDD4C8",
        sidebar_background: "#25190F",
        sidebar_text: "#E8E2DB",
        sidebar_text_muted: "#A8998C",
        rail_background: "#1A1109",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "mocha",
        name: "Mocha",
        primary: "#A0522D",
        accent: "#C58A5E",
        warning: "#D89A4E",
        error: "#B5453B",
        background: "#F7F3F0",
        surface: "#EDE7E2",
        surface_dark: "#E2DAD3",
        text: "#2A2220",
        text_muted: "#6B5E58",
        border: "#DAD0C8",
        sidebar_background: "#2E2422",
        sidebar_text: "#E6DCD6",
        sidebar_text_muted: "#A38F86",
        rail_background: "#211A18",
        selection_background: "",
        selection_foreground: "",
    },
    Palette {
        id: "nocturne",
        name: "Nocturne",
        primary: "#4F9CD9",
        accent: "#4FB477",
        warning: "#E0B14F",
        error: "#E0556B",
        background: "#0F1620",
        surface: "#18222F",
        surface_dark: "#0A0F16",
        text: "#C3CCD9",
        text_muted: "#66717F",
        border: "#1F2C3A",
        sidebar_background: "#1A2736",
        sidebar_text: "",
        sidebar_text_muted: "",
        rail_background: "#0A0F16",
        selection_background: "",
        selection_foreground: "",
    },
];

pub(super) fn lookup(name: &str) -> Option<&'static Palette> {
    let normalized = normalize(name);
    PALETTES
        .iter()
        .find(|palette| palette.id == normalized || normalize(palette.name) == normalized)
}

fn normalize(value: &str) -> String {
    let mut normalized = String::new();
    let mut separator = false;
    for character in value.trim().chars().flat_map(char::to_lowercase) {
        let character = match character {
            'á' | 'à' | 'â' | 'ä' => Some('a'),
            'é' | 'è' | 'ê' | 'ë' => Some('e'),
            'í' | 'ì' | 'î' | 'ï' => Some('i'),
            'ó' | 'ò' | 'ô' | 'ö' => Some('o'),
            'ú' | 'ù' | 'û' | 'ü' => Some('u'),
            value if value.is_ascii_alphanumeric() => Some(value),
            _ => None,
        };
        if let Some(character) = character {
            if separator && !normalized.is_empty() {
                normalized.push('-');
            }
            normalized.push(character);
            separator = false;
        } else {
            separator = true;
        }
    }
    normalized
}
